### ISSUE TITLE
我测试网络节点已经跑通...正常运转...可是如何模拟挖矿...如何获取coin呢？

### ISSUE THREAD

**Issue by dllio** [excelsia/vee#121]
我测试网络节点已经跑通...正常运转...可是如何模拟挖矿...如何获取coin呢？ @sunnyking

**Comment by MarvelZHANG** [comment]
Hi dllio，
您可以关注我们的reddit账号：https://www.reddit.com/user/VEE_tech_VVV
上面有一个VEE Testnet Coins Request的帖子，在下面回复就可以获得VEE coin了

**Comment by MarvelZHANG** [comment]
模拟挖矿您需要先在我们的API中contend 一个minting slot，然后配置节点账号为拥有minting slot的账号，重启就能自动开始挖矿了

**Comment by dllio** [comment]
> 模拟挖矿您需要先在我们的API中contend 一个minting slot，然后配置节点账号为拥有minting slot的账号，重启就能自动开始挖矿了

api的地址是？

**Comment by ncying** [comment]
@dllio if you joined the p2p network, you can go to localhost:9922 and POST /spos/contend to get the minting right
btw, it is better to choose a free slot id in API GET /consensus/allSlotsInfo

**Comment by dllio** [comment]
interval-after-last-block-then-generation-is-allowed 
这个参数大概是什么意思呢？默认情况下节点启动同步到最新区块后的， 120 小时后才能挖矿?

**Comment by ncying** [comment]
@dllio you will mint block when your local block is updated. 120h means if your block data is too old, it will only download the block. when cnt_time - last_local_block_time < 120h, your minter will be activate and ready to mint
