### ISSUE TITLE
the problem of set up the super node

### ISSUE THREAD

**Issue by duxiaoer** [excelsia/vee#127]
"Now it's time to check your vee config! It's embedded into the deb package and unpacked to /usr/share/vee-testnet/conf/vee.conf and symlinked to /etc/vee-testnet/vee.conf. Please read this and edit vee config with caution."
How should I operate this step?

**Comment by VeeSheldonYang** [comment]
Just use your favourite text editor (vi, nano, etc.) to modify with your own config. For example:

```
sudo vi /etc/vee-testnet/vee.conf
```

**Some key points of configuration**
* The **directory** should be set to your own path. If you have your own wallet.dat file, create or replace the file `<your path>/.vee-testnet/wallet/wallet.dat`

* It is better to choose more than 3 peers to fill the **known-peers** field. You could check known-peers via VEE explorer. Some known-peers for current reference:

	```
	# For TestNet
	known-peers = ["18.179.34.202:9923", "13.250.53.12:9923", "18.188.219.229:9923"]
	```

* For security reason, it is better to set you own **api-key-hash**. You could check the hash by this command

	```
	curl -X POST -d '<your api key>' 'https://wallettestnet.vee.tech/api/utils/hash/secure'
	```

**Comment by VeeSheldonYang** [comment]
Issue solved.
