### ISSUE TITLE
No such files and directory.

### ISSUE THREAD

**Issue by DreamXzxy** [excelsia/vee#128]
![image](https://user-images.githubusercontent.com/17998878/48113206-c7cdf180-e294-11e8-8d2e-d802475260a9.png)

**Comment by ncying** [comment]
you should download the deb file from https://github.com/excelsia/vee/releases.

and the file name is 'vee_0.1.0_all.deb' or 'vee_0.1.0_all_testnet.deb'

we suggest to use Ubuntu OS for ded installation.
